/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package service;

import javax.swing.JOptionPane;

/**
 *
 * @author Hernandez Fernando
 */
public class Conversor extends javax.swing.JFrame {

    /**
     * Creates new form Conversor
     */
    public Conversor() {
        initComponents();
        setTitle("De celcius a Farenheit");
        setResizable(false);
        setSize(800, 600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanelNorth = new javax.swing.JPanel();
        jPanelSouth = new javax.swing.JPanel();
        jPanelEast = new javax.swing.JPanel();
        jPanelWest = new javax.swing.JPanel();
        jPanelCenter = new javax.swing.JPanel();
        jLabelConversor = new javax.swing.JLabel();
        jButtonConvertir = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        jLabelIngrese = new javax.swing.JLabel();
        jTextFieldCelcius = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setLayout(new java.awt.BorderLayout());

        jPanelNorth.setOpaque(false);
        jPanelNorth.setPreferredSize(new java.awt.Dimension(69, 69));

        javax.swing.GroupLayout jPanelNorthLayout = new javax.swing.GroupLayout(jPanelNorth);
        jPanelNorth.setLayout(jPanelNorthLayout);
        jPanelNorthLayout.setHorizontalGroup(
            jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelNorthLayout.setVerticalGroup(
            jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jDesktopPane1.add(jPanelNorth, java.awt.BorderLayout.NORTH);

        jPanelSouth.setOpaque(false);
        jPanelSouth.setPreferredSize(new java.awt.Dimension(69, 69));

        javax.swing.GroupLayout jPanelSouthLayout = new javax.swing.GroupLayout(jPanelSouth);
        jPanelSouth.setLayout(jPanelSouthLayout);
        jPanelSouthLayout.setHorizontalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelSouthLayout.setVerticalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jDesktopPane1.add(jPanelSouth, java.awt.BorderLayout.SOUTH);

        jPanelEast.setOpaque(false);
        jPanelEast.setPreferredSize(new java.awt.Dimension(69, 69));

        javax.swing.GroupLayout jPanelEastLayout = new javax.swing.GroupLayout(jPanelEast);
        jPanelEast.setLayout(jPanelEastLayout);
        jPanelEastLayout.setHorizontalGroup(
            jPanelEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        jPanelEastLayout.setVerticalGroup(
            jPanelEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jDesktopPane1.add(jPanelEast, java.awt.BorderLayout.EAST);

        jPanelWest.setOpaque(false);
        jPanelWest.setPreferredSize(new java.awt.Dimension(69, 69));

        javax.swing.GroupLayout jPanelWestLayout = new javax.swing.GroupLayout(jPanelWest);
        jPanelWest.setLayout(jPanelWestLayout);
        jPanelWestLayout.setHorizontalGroup(
            jPanelWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        jPanelWestLayout.setVerticalGroup(
            jPanelWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jDesktopPane1.add(jPanelWest, java.awt.BorderLayout.WEST);

        jPanelCenter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanelCenter.setLayout(new java.awt.BorderLayout());

        jLabelConversor.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelConversor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConversor.setText("Conversor de temperatura");
        jLabelConversor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelCenter.add(jLabelConversor, java.awt.BorderLayout.PAGE_START);

        jButtonConvertir.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButtonConvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/service/images/icons8-aprobar-y-actualizar-48.png"))); // NOI18N
        jButtonConvertir.setText("Convertir");
        jButtonConvertir.setPreferredSize(new java.awt.Dimension(10, 70));
        jButtonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirActionPerformed(evt);
            }
        });
        jPanelCenter.add(jButtonConvertir, java.awt.BorderLayout.PAGE_END);

        jPanel.setLayout(new java.awt.GridBagLayout());

        jLabelIngrese.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelIngrese.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIngrese.setText("Ingrese la temperatura en grados celcius: ");
        jLabelIngrese.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel.add(jLabelIngrese, new java.awt.GridBagConstraints());

        jTextFieldCelcius.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldCelcius.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldCelcius.setPreferredSize(new java.awt.Dimension(100, 28));
        jPanel.add(jTextFieldCelcius, new java.awt.GridBagConstraints());

        jPanelCenter.add(jPanel, java.awt.BorderLayout.CENTER);

        jDesktopPane1.add(jPanelCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirActionPerformed
        // TODO add your handling code here:
        try {
            double celcius = Double.parseDouble(jTextFieldCelcius.getText());
            JOptionPane.showMessageDialog(this, "La temperatura en grados Farenheit es: " + (celcius * 9 / 5 + 32));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un numero valido");
        }
    }//GEN-LAST:event_jButtonConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelConversor;
    private javax.swing.JLabel jLabelIngrese;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelEast;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JPanel jPanelWest;
    private javax.swing.JTextField jTextFieldCelcius;
    // End of variables declaration//GEN-END:variables
}
