/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import javax.swing.JOptionPane;

/**
 *
 * @author Hernandez Fernando
 */
public class Credenciales extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Credenciales() {
        initComponents();
        setTitle("Credenciales");
        setSize(800, 630);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSouth = new javax.swing.JPanel();
        jButtonOcultar = new javax.swing.JButton();
        jButtonVer = new javax.swing.JButton();
        jDesktopPaneCenter = new javax.swing.JDesktopPane();
        jLabelIncioSesion = new javax.swing.JLabel();
        jPanelCenter = new javax.swing.JPanel();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabelContrasenia = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonVerificar = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jMenuBarNorth = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSouth.setBackground(new java.awt.Color(255, 255, 255));

        jButtonOcultar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonOcultar.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jButtonOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons7-ocultar-contraseña-50.png"))); // NOI18N
        jButtonOcultar.setText("Ocultar");
        jButtonOcultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonOcultar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonOcultar.setPreferredSize(new java.awt.Dimension(200, 130));
        jButtonOcultar.setVerifyInputWhenFocusTarget(false);
        jButtonOcultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcultarActionPerformed(evt);
            }
        });
        jPanelSouth.add(jButtonOcultar);

        jButtonVer.setBackground(new java.awt.Color(204, 204, 204));
        jButtonVer.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jButtonVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons7-mostrar-contraseña-50.png"))); // NOI18N
        jButtonVer.setText("Ver");
        jButtonVer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVer.setHideActionText(true);
        jButtonVer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonVer.setIconTextGap(10);
        jButtonVer.setPreferredSize(new java.awt.Dimension(200, 130));
        jButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerActionPerformed(evt);
            }
        });
        jPanelSouth.add(jButtonVer);

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.PAGE_END);

        jDesktopPaneCenter.setLayout(new java.awt.BorderLayout());

        jLabelIncioSesion.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabelIncioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIncioSesion.setText("Inicio de sesion");
        jLabelIncioSesion.setOpaque(true);
        jLabelIncioSesion.setVerifyInputWhenFocusTarget(false);
        jDesktopPaneCenter.add(jLabelIncioSesion, java.awt.BorderLayout.NORTH);

        jPanelCenter.setDoubleBuffered(false);
        jPanelCenter.setOpaque(false);
        jPanelCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelContrasenia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelContrasenia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelContrasenia.setText("Contrasenia:");
        jPanelPrincipal.add(jLabelContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 160, 40));

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUsuario.setText("Usuario:");
        jPanelPrincipal.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 160, 40));

        jTextFieldUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelPrincipal.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 340, 40));

        jButtonVerificar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonVerificar.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jButtonVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-cliente-windows-48.png"))); // NOI18N
        jButtonVerificar.setText("Verificar");
        jButtonVerificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVerificar.setIconTextGap(10);
        jButtonVerificar.setPreferredSize(new java.awt.Dimension(200, 130));
        jButtonVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificarActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(jButtonVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 200, -1));

        jPasswordField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelPrincipal.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 340, 40));

        jPanelCenter.add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 730, 320));

        jDesktopPaneCenter.add(jPanelCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(jDesktopPaneCenter, java.awt.BorderLayout.CENTER);

        jMenuFile.setText("File");
        jMenuBarNorth.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuBarNorth.add(jMenuEdit);

        setJMenuBar(jMenuBarNorth);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcultarActionPerformed
        // TODO add your handling code here:
        jPasswordField.setEchoChar('*');
    }//GEN-LAST:event_jButtonOcultarActionPerformed

    private void jButtonVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificarActionPerformed
        // TODO add your handling code here:
        String email = jTextFieldUsuario.getText();
        char[] passwordChars = jPasswordField.getPassword();
        String password = new String(passwordChars);
        
        if (email.equals("alumno@ulp.edu.ar") && password.equals("12345678")) {
            JOptionPane.showMessageDialog(this, "Bienvenido");
        }else {
            JOptionPane.showMessageDialog(this, "Usuario y/o contrasenia incorrectas");
        }
    }//GEN-LAST:event_jButtonVerificarActionPerformed

    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed
        // TODO add your handling code here:
        jPasswordField.setEchoChar((char) 0);
    }//GEN-LAST:event_jButtonVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credenciales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOcultar;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JButton jButtonVerificar;
    private javax.swing.JDesktopPane jDesktopPaneCenter;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabelIncioSesion;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenuBar jMenuBarNorth;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
