/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

/**
 *
 * @author Hernandez Fernando
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSouth = new javax.swing.JPanel();
        jButtonOcultar = new javax.swing.JButton();
        jButtonVer = new javax.swing.JButton();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBarNorth = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonOcultar.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jButtonOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons7-ocultar-contraseña-50.png"))); // NOI18N
        jButtonOcultar.setText("Ocultar");
        jButtonOcultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonOcultar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonOcultar.setIconTextGap(10);
        jButtonOcultar.setPreferredSize(new java.awt.Dimension(200, 130));
        jButtonOcultar.setVerifyInputWhenFocusTarget(false);
        jButtonOcultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcultarActionPerformed(evt);
            }
        });
        jPanelSouth.add(jButtonOcultar);

        jButtonVer.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jButtonVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons7-mostrar-contraseña-50.png"))); // NOI18N
        jButtonVer.setText("Ver");
        jButtonVer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVer.setHideActionText(true);
        jButtonVer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonVer.setIconTextGap(10);
        jButtonVer.setPreferredSize(new java.awt.Dimension(200, 130));
        jPanelSouth.add(jButtonVer);

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane, java.awt.BorderLayout.CENTER);

        jMenuFile.setText("File");
        jMenuBarNorth.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuBarNorth.add(jMenuEdit);

        setJMenuBar(jMenuBarNorth);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOcultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOcultar;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenuBar jMenuBarNorth;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JPanel jPanelSouth;
    // End of variables declaration//GEN-END:variables
}
